### ISSUE TITLE
ReflectionHelper doesn't recognize Craftbukkit Version 1.18.2

### ISSUE THREAD

**Issue by bluestormhunter** [BlackDemonZyT/BotSentry#76] opened 2022-03-07 23:51 UTC
Not sure how critical this is, as I have not been able to test the full functionality of the plugin. These Warnings show up when using the latest purpur build for Version 1.18.2:

[00:48:05 INFO]: [BotSentry] Enabling BotSentry v9.4.2-THANATOS
[00:48:05 INFO]: [ReflectionHelper/MinecraftVersion] I am loaded from package org.inventivetalent.packetlistener.reflection.minecraft
[00:48:05 ERROR]: [ReflectionHelper/MinecraftVersion] Failed to find version enum for 'org.bukkit.craftbukkit.v1_18_R2'/'v1_18_R2'
[00:48:05 INFO]: [ReflectionHelper/MinecraftVersion] Generating dynamic constant...
[00:48:05 INFO]: [ReflectionHelper/MinecraftVersion] Injected dynamic version v1_18_R2 (#11802).
[00:48:05 INFO]: [ReflectionHelper/MinecraftVersion] Please inform inventivetalent about the outdated version, as this is not guaranteed to work.
[00:48:05 INFO]: [ReflectionHelper/MinecraftVersion] Version is v1_18_R2 (11802)
[00:48:05 ERROR]: [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_18_R2'/'v1_18_R2'
[00:48:05 INFO]: [ReflectionHelper] Generating dynamic constant...
[00:48:05 WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='constructorAccessor', types=[]}] in class class java.lang.reflect.Constructor
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.resolve(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.newEnumInstance(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft$Version.getVersion(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(Unknown Source)
[00:48:05 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[00:48:05 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.ChannelInjector.inject(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//org.inventivetalent.packetlistener.PacketListenerAPI.load(Unknown Source)
[00:48:05 WARN]:        at BotSentry-9.4.2-THANATOS-SpigotMC.jar//com.lahuca.botsentry.spigot.BotSentrySpigot.onEnable(Unknown Source)
[00:48:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:48:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[00:48:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[00:48:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[00:48:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[00:48:05 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[00:48:05 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438)
[00:48:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[00:48:05 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1181)
[00:48:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[00:48:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:48:05 INFO]: [PacketListenerAPI] Using INChannel
[00:48:05 INFO]: Injected custom channel handlers.

**Comment by ilfarpro** [comment] 2022-04-19 21:23
I have the same issue, not sure if it's safe to use BotSentry with this warnings. Hope it will be fixed soon.

**Comment by Laurenshup** [comment] 2022-04-20 07:12
As announced in the Discord. It is very safe to use BotSentry, these are warnings. In the upcoming version, they will be fixed. BotSentry still works as intended.

**Comment by Laurenshup** [comment] 2022-06-10 15:05
This has been fixed in the code, I have immediately fixed it for 1.19 as well.

**Closed by Laurenshup** 2022-06-10 15:05 UTC
Labels: bug
