### ISSUE TITLE
Username whitelist and permission bypass.

### ISSUE THREAD

**Issue by NotYusta** [BlackDemonZyT/BotSentry#57] opened 2021-11-21 03:21 UTC
add username whitelist and permission bypass when the antibot attack is on rather than only an IP whitelist because you'll need to ask the player's ip to join.

**Comment by Laurenshup** [comment] 2022-01-23 20:15
I will not add the permission bypass for the following two reasons:
* At login initialisation there is no data of the player available yet. Permissions cannot be retrieved.
* Permissions are managed by other plugins, we try to keep everything sorted out so bots do not consume unnecessary data.

**Comment by Laurenshup** [comment] 2022-01-23 20:16
Looks like this is also a duplicate of #54. Any news will be followed there.

**Closed by Laurenshup** 2022-01-23 20:16 UTC
Labels: suggestion, good first issue, medium priority
