### ISSUE TITLE
[Really Important] Heavy CPU leak somewhere in Bot-Sentry CPU usage only way up

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#18] opened 2021-04-24 18:18 UTC
In a clean bungeecord installation with just Bot-Sentry on it, there a CPU leak, reported by already 2 customers, i checked in the test server and profiled it, the profile link is here: [](https://spark.lucko.me/sM8v2WTzyP)

When attack starts theres a bit of a high cpu usage for just a 1000 bots per second attack theres 40% cpu usage, and, after 2-5 minutes, cpu usage goes to 100%, after 5 minutes goes to 400%. Always follows the same pattern. Ram usage is alright and ultra stable.

As you can see in the profiler, all other processes takes 19.000ms or less, but Bot-Sentry processes takes +300.000ms

As seen in this pictures: https://imgur.com/a/t444wyd

**Comment by Laurenshup** [comment] 2021-04-27 13:28
Profiling:
https://spark.lucko.me/8Qr6pcyYPH
https://spark.lucko.me/TbOV5NOL2G
https://spark.lucko.me/GkdVaHnoQl

**Comment by Laurenshup** [comment] 2021-04-27 13:32
After investigating this, this might be a problem with threading. As you can see in the profiling logs, all plugins randomly consume extra CPU. Pretty sure this is because of enormous amount of threads that are caused by the big amount of logins and packets.

**Comment by Laurenshup** [comment] 2021-04-29 08:37
After many testing we have found out that the problem is inside the Amazon detection. We have applied a fix and it it working on BungeeCord, Velocity & Sponge. Only testing needed on Spigot.

**Comment by Laurenshup** [comment] 2021-04-30 15:23
After many investigation, this issue has been fixed on all platforms.

**Closed by Laurenshup** 2021-04-30 15:23 UTC
Labels: bug, high priority
