### ISSUE TITLE
Lockdown time going negative

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#17] opened 2021-04-24 15:12 UTC
https://prnt.sc/11z9fxi

**Comment by Laurenshup** [comment] 2021-04-26 17:54
Need more information. Did the attack really take 53130 seconds already?

**Comment by BlackDemonZyT** [comment] 2021-04-27 08:23
> Need more information. Did the attack really take 53130 seconds already?

Unfortunately i don't know, i don't remember the guy that reported this to ask him, but it don't think the attack took 14 hours xD

**Comment by Laurenshup** [comment] 2021-04-27 13:03
I cannot reproduce this issue. There is no real way of this happening on the newest version.

**Comment by Laurenshup** [comment] 2021-04-27 13:25
I saw you said this is from the latest version in WhatsApp. Can you really confirm that?

**Comment by Laurenshup** [comment] 2021-04-30 15:25
@BlackDemonZyT As you do not know any more details, I sadly cannot finish this.

**Comment by BlackDemonZyT** [comment] 2021-04-30 16:04
If a next user reports this, we will be able to reproduce it better.

**Comment by Laurenshup** [comment] 2021-04-30 16:12
Will close this for now. If more information is available, we can open it again.

**Closed by Laurenshup** 2021-04-30 16:12 UTC
Labels: bug, medium priority, question
