### ISSUE TITLE
Issue with latest version of Velocity 3.0.1

### ISSUE THREAD

**Issue by KamaArtz** [BlackDemonZyT/BotSentry#56] opened 2021-11-20 16:57 UTC
With last version of Velocity (3.0.1), I get an error in the console on each player's join, this is the error:
https://pastebin.com/HVpXnbPC

**Comment by Laurenshup** [comment] 2021-11-29 13:48
This issue has been causing errors because of changes into the Velocity API. Upcoming version of BotSentry will have this fixed. Aiming to be released before the end of the year. For now I recommend people not using the latest version of Velocity (I know this is a bad solution).

In the upcoming version we will only start supporting Velocity 3.0.1, meaning other servers will have to update their proxy servers. This is to enhance the security and stability.

**Comment by Kapitowa** [comment] 2021-12-01 21:04
So we should wait until the end of the year? It's sounds pretty bad

**Comment by Laurenshup** [comment] 2021-12-01 21:19
We are actively working on it. As stated, it will be released before the end of the year.

**Comment by Laurenshup** [comment] 2021-12-03 17:39
This has now been fixed in the upcoming version (release before 2022). Confirmed it works on Velocity 3.1.0 build 95.

**Closed by Laurenshup** 2021-12-03 17:39 UTC
Labels: bug, good first issue, high priority

**Comment by KamaArtz** [comment] 2021-12-04 21:59
Oh perfect! Yeah I switched to velocity 3.1.0 too, so I really hope it's fixed and I can't wait for this update to come out.

**Comment by Laurenshup** [comment] 2021-12-04 22:44
Most likely will be tomorrow (5 December).
