### ISSUE TITLE
Check Bedrock players (GeyserMC + floodgate) on Velocity

### ISSUE THREAD

**Issue by GenifeYouTube** [BlackDemonZyT/BotSentry#28] opened 2021-05-15 05:20 UTC
Hello. BotSentry does not check the players from the bedrock on velocity (does not analyze the connection of the player from the bedrock and the rest). If you block the IP address of the player who plays from bedrock (using floodgate the server gets the real ip of the bedrock player), then the player kicks from the server with the message that his IP has been banned using BotSentry and when reconnected he can safely connect. At Bungeecord (Waterfall) everything is as it should be, no problem. This only happens with Velocity.

Sorry my english is bad:)

**Comment by Laurenshup** [comment] 2021-05-15 08:42
Thank you for reporting. I think it is odd that it does not work on Velocity. Can you give me your config.yml?

**Comment by GenifeYouTube** [comment] 2021-05-21 14:21
I checked something, it only happens when using velocity and floodgate (I have 2.0), without using floodgate BotSentry checks bedrock players.

**Comment by GenifeYouTube** [comment] 2021-05-21 14:21
ONLY when using floodgate

**Comment by Laurenshup** [comment] 2021-06-16 19:27
I cannot reproduce this problem myself. Do you mind sending your configuration files of BotSentry, Geyser & Floodgate?

**Comment by Laurenshup** [comment] 2021-09-08 15:27
Any more information about this issue?

**Comment by Laurenshup** [comment] 2021-12-04 17:25
I am closing this, due to the lack of information.

**Closed by Laurenshup** 2021-12-04 17:25 UTC
Labels: bug, good first issue, question, medium priority
